# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Paso 1 - Descargar el repositorio
      uses: actions/checkout@v2
    - name: Paso 2 - Instalar JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        #Añadimos las dependencias al cache para que sean mas rapidas las siguientes ejecuciones
        cache: maven
    - name: Paso 3 - Build con maven el projecto
      run: mvn -B package --file pom.xml
    #Crear carpeta donde se guardaran los artefactos
    #- run: mkdir staging && cp target/*.jar staging
    - name: Paso 4 - Guardar los resultados de los test en actefactos
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Result 
        path: target/surefire-reports/*.xml
